[build]
  command = ""
  publish = "."

[[redirects]]
  # Cloudflare Workers 后端地址
  # 所有 /api/* 请求会被代理到 Cloudflare Workers
  from = "/api/*"
  to = "https://api.railfair.uk/api/:splat"
  status = 200
  force = true

